// Code generated by MockGen. DO NOT EDIT.
// Source: email_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=email_history_repository.go -destination=../../tests/mock/datastore/email_history_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
