// Code generated by MockGen. DO NOT EDIT.
// Source: damage_level_repository.go
//
// Generated by this command:
//
//	mockgen -source=damage_level_repository.go -destination=../../../tests/mock/datastore/damage_level_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
