// Code generated by MockGen. DO NOT EDIT.
// Source: disaster_repository.go
//
// Generated by this command:
//
//	mockgen -source=disaster_repository.go -destination=../../../tests/mock/datastore/disaster_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore

import (
	context "context"
	reflect "reflect"

	model "github.com/AI1411/fullstack-react-go/internal/domain/model"
	datastore "github.com/AI1411/fullstack-react-go/internal/infra/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockDisasterRepository is a mock of DisasterRepository interface.
type MockDisasterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDisasterRepositoryMockRecorder
	isgomock struct{}
}

// MockDisasterRepositoryMockRecorder is the mock recorder for MockDisasterRepository.
type MockDisasterRepositoryMockRecorder struct {
	mock *MockDisasterRepository
}

// NewMockDisasterRepository creates a new mock instance.
func NewMockDisasterRepository(ctrl *gomock.Controller) *MockDisasterRepository {
	mock := &MockDisasterRepository{ctrl: ctrl}
	mock.recorder = &MockDisasterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisasterRepository) EXPECT() *MockDisasterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDisasterRepository) Create(ctx context.Context, disaster *model.Disaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, disaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDisasterRepositoryMockRecorder) Create(ctx, disaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDisasterRepository)(nil).Create), ctx, disaster)
}

// Delete mocks base method.
func (m *MockDisasterRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDisasterRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDisasterRepository)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockDisasterRepository) Find(ctx context.Context, params *datastore.DisasterSearchParams) ([]*model.Disaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, params)
	ret0, _ := ret[0].([]*model.Disaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDisasterRepositoryMockRecorder) Find(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDisasterRepository)(nil).Find), ctx, params)
}

// FindByID mocks base method.
func (m *MockDisasterRepository) FindByID(ctx context.Context, id string) (*model.Disaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Disaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDisasterRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDisasterRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockDisasterRepository) Update(ctx context.Context, disaster *model.Disaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, disaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDisasterRepositoryMockRecorder) Update(ctx, disaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDisasterRepository)(nil).Update), ctx, disaster)
}
