// Code generated by MockGen. DO NOT EDIT.
// Source: facility_equipment_repository.go
//
// Generated by this command:
//
//	mockgen -source=facility_equipment_repository.go -destination=../../../tests/mock/datastore/facility_equipment_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
