// Code generated by MockGen. DO NOT EDIT.
// Source: notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=notification_repository.go -destination=../../../tests/mock/datastore/notification_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
