// Code generated by MockGen. DO NOT EDIT.
// Source: organization_repository.go
//
// Generated by this command:
//
//	mockgen -source=organization_repository.go -destination=../../../tests/mock/datastore/organization_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
