// Code generated by MockGen. DO NOT EDIT.
// Source: prefecture_repository.go
//
// Generated by this command:
//
//	mockgen -source=prefecture_repository.go -destination=../../../tests/mock/datastore/prefecture_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
