// Code generated by MockGen. DO NOT EDIT.
// Source: support_application_repository.go
//
// Generated by this command:
//
//	mockgen -source=support_application_repository.go -destination=../../../tests/mock/datastore/support_application_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
