// Code generated by MockGen. DO NOT EDIT.
// Source: timeline_repository.go
//
// Generated by this command:
//
//	mockgen -source=timeline_repository.go -destination=../../../tests/mock/datastore/timeline_repository.mock.go
//

// Package mock_datastore is a generated GoMock package.
package mock_datastore
