// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAssessmentComment = "assessment_comments"

// AssessmentComment mapped from table <assessment_comments>
type AssessmentComment struct {
	ID              int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:コメントID - 主キー" json:"id"`                                                                             // コメントID - 主キー
	AssessmentID    int32          `gorm:"column:assessment_id;type:integer;not null;index:idx_assessment_comments_assessment_id,priority:1;comment:査定ID - 関連する査定のID" json:"assessment_id"`                 // 査定ID - 関連する査定のID
	UserID          string         `gorm:"column:user_id;type:uuid;not null;index:idx_assessment_comments_user_id,priority:1;comment:ユーザーID - コメントを投稿したユーザーのID" json:"user_id"`                             // ユーザーID - コメントを投稿したユーザーのID
	CommentText     string         `gorm:"column:comment_text;type:text;not null;comment:コメント本文 - コメントの内容" json:"comment_text"`                                                                             // コメント本文 - コメントの内容
	CommentTime     time.Time      `gorm:"column:comment_time;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:コメント時間 - コメントが投稿された時間" json:"comment_time"`                          // コメント時間 - コメントが投稿された時間
	ParentCommentID *int32         `gorm:"column:parent_comment_id;type:integer;index:idx_assessment_comments_parent_comment_id,priority:1;comment:親コメントID - 返信先のコメントID（スレッド構造用）" json:"parent_comment_id"` // 親コメントID - 返信先のコメントID（スレッド構造用）
	CreatedAt       time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`                                    // 作成日時 - レコード作成日時
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`                                  // 更新日時 - レコード最終更新日時
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:削除日時 - 論理削除用のタイムスタンプ" json:"deleted_at"`                                                                  // 削除日時 - 論理削除用のタイムスタンプ
}

// TableName AssessmentComment's table name
func (*AssessmentComment) TableName() string {
	return TableNameAssessmentComment
}
