// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDamageLevel = "damage_levels"

// DamageLevel mapped from table <damage_levels>
type DamageLevel struct {
	ID          int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:被害程度ID - 主キー" json:"id"`                                                   // 被害程度ID - 主キー
	Name        string    `gorm:"column:name;type:character varying(50);not null;index:idx_damage_levels_name,priority:1;comment:被害程度名 - 軽微, 中程度, 深刻, 甚大など" json:"name"` // 被害程度名 - 軽微, 中程度, 深刻, 甚大など
	Description *string   `gorm:"column:description;type:text;comment:説明 - 被害程度の詳細説明" json:"description"`                                                                // 説明 - 被害程度の詳細説明
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`          // 作成日時 - レコード作成日時
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`        // 更新日時 - レコード最終更新日時
}

// TableName DamageLevel's table name
func (*DamageLevel) TableName() string {
	return TableNameDamageLevel
}
