// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDisasterDocument = "disaster_documents"

// DisasterDocument mapped from table <disaster_documents>
type DisasterDocument struct {
	ID           int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:書類ID - 主キー" json:"id"`                                                                                                                 // 書類ID - 主キー
	DisasterID   string         `gorm:"column:disaster_id;type:uuid;not null;index:idx_disaster_documents_disaster_id,priority:1;comment:災害ID - 関連する災害のID" json:"disaster_id"`                                                             // 災害ID - 関連する災害のID
	Title        string         `gorm:"column:title;type:character varying(255);not null;comment:書類タイトル - 文書の名称" json:"title"`                                                                                                             // 書類タイトル - 文書の名称
	DocumentType string         `gorm:"column:document_type;type:character varying(50);not null;index:idx_disaster_documents_document_type,priority:1;comment:書類種別 - 報告書, 写真, 申請書, 証明書など" json:"document_type"`                            // 書類種別 - 報告書, 写真, 申請書, 証明書など
	FilePath     string         `gorm:"column:file_path;type:character varying(500);not null;comment:ファイルパス - ファイルの保存場所" json:"file_path"`                                                                                                 // ファイルパス - ファイルの保存場所
	MimeType     string         `gorm:"column:mime_type;type:character varying(100);not null;comment:MIMEタイプ - ファイルの形式を示すMIMEタイプ" json:"mime_type"`                                                                                        // MIMEタイプ - ファイルの形式を示すMIMEタイプ
	Description  *string        `gorm:"column:description;type:text;comment:説明 - ファイルの説明や備考" json:"description"`                                                                                                                           // 説明 - ファイルの説明や備考
	UploadedBy   string         `gorm:"column:uploaded_by;type:character varying(255);not null;comment:アップロード者 - ファイルをアップロードしたユーザー名" json:"uploaded_by"`                                                                                   // アップロード者 - ファイルをアップロードしたユーザー名
	IsPublic     bool           `gorm:"column:is_public;type:boolean;not null;comment:公開フラグ - 一般公開するかどうか" json:"is_public"`                                                                                                                // 公開フラグ - 一般公開するかどうか
	UploadDate   time.Time      `gorm:"column:upload_date;type:timestamp without time zone;not null;index:idx_disaster_documents_upload_date,priority:1;default:CURRENT_TIMESTAMP;comment:アップロード日時 - ファイルがアップロードされた日時" json:"upload_date"` // アップロード日時 - ファイルがアップロードされた日時
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`                                                                   // 作成日時 - レコード作成日時
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`                                                                 // 更新日時 - レコード最終更新日時
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone;comment:削除日時 - 論理削除用のタイムスタンプ" json:"deleted_at"`                                                                                                 // 削除日時 - 論理削除用のタイムスタンプ
	Disaster     Disaster       `json:"disaster"`
}

// TableName DisasterDocument's table name
func (*DisasterDocument) TableName() string {
	return TableNameDisasterDocument
}
