// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDisasterType = "disaster_types"

// DisasterType mapped from table <disaster_types>
type DisasterType struct {
	ID          int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:災害種別ID - 主キー" json:"id"`                                                                      // 災害種別ID - 主キー
	Name        string    `gorm:"column:name;type:character varying(50);not null;index:idx_disaster_types_name,priority:1;comment:災害種別名 - 洪水, 地滑り, 雹害, 干ばつ, 風害, 地震, 霜害, 病害虫など" json:"name"` // 災害種別名 - 洪水, 地滑り, 雹害, 干ばつ, 風害, 地震, 霜害, 病害虫など
	Description *string   `gorm:"column:description;type:text;comment:説明 - 災害種別の詳細説明" json:"description"`                                                                                   // 説明 - 災害種別の詳細説明
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`                             // 作成日時 - レコード作成日時
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`                           // 更新日時 - レコード最終更新日時
}

// TableName DisasterType's table name
func (*DisasterType) TableName() string {
	return TableNameDisasterType
}
