// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGisDatum = "gis_data"

// GisDatum mapped from table <gis_data>
type GisDatum struct {
	ID           int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:GISデータID - 主キー" json:"id"`                                                   // GISデータID - 主キー
	DisasterID   string         `gorm:"column:disaster_id;type:uuid;not null;index:idx_gis_data_disaster_id,priority:1;comment:災害ID - 関連する災害のID" json:"disaster_id"`             // 災害ID - 関連する災害のID
	DataType     string         `gorm:"column:data_type;type:character varying(50);not null;index:idx_gis_data_data_type,priority:1;comment:データ種別 - GISデータの種類" json:"data_type"` // データ種別 - GISデータの種類
	Name         string         `gorm:"column:name;type:character varying(100);not null;comment:名称 - GISデータの名称" json:"name"`                                                     // 名称 - GISデータの名称
	Description  *string        `gorm:"column:description;type:text;comment:説明 - GISデータの説明" json:"description"`                                                                  // 説明 - GISデータの説明
	GeometryType string         `gorm:"column:geometry_type;type:character varying(20);not null;comment:ジオメトリ種別 - 地理データの形状タイプ" json:"geometry_type"`                             // ジオメトリ種別 - 地理データの形状タイプ
	GeometryData string         `gorm:"column:geometry_data;type:text;not null;comment:ジオメトリデータ - GeoJSON形式の地理データ" json:"geometry_data"`                                         // ジオメトリデータ - GeoJSON形式の地理データ
	Properties   *string        `gorm:"column:properties;type:jsonb;comment:プロパティ - 追加のプロパティ情報（JSON形式）" json:"properties"`                                                       // プロパティ - 追加のプロパティ情報（JSON形式）
	CreatedBy    string         `gorm:"column:created_by;type:uuid;not null;index:idx_gis_data_created_by,priority:1;comment:作成者ID - データを作成したユーザーのID" json:"created_by"`         // 作成者ID - データを作成したユーザーのID
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`            // 作成日時 - レコード作成日時
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`          // 更新日時 - レコード最終更新日時
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:削除日時 - 論理削除用のタイムスタンプ" json:"deleted_at"`                                          // 削除日時 - 論理削除用のタイムスタンプ
}

// TableName GisDatum's table name
func (*GisDatum) TableName() string {
	return TableNameGisDatum
}
