// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	ID           int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:組織ID - 主キー" json:"id"`                                                     // 組織ID - 主キー
	Name         string         `gorm:"column:name;type:character varying(100);not null;index:idx_organizations_name,priority:1;comment:組織名 - 組織の名称" json:"name"`              // 組織名 - 組織の名称
	Type         string         `gorm:"column:type;type:character varying(50);not null;index:idx_organizations_type,priority:1;comment:組織種別 - 国, 都道府県, 市町村, JAなど" json:"type"` // 組織種別 - 国, 都道府県, 市町村, JAなど
	PrefectureID *int32         `gorm:"column:prefecture_id;type:integer;index:idx_organizations_prefecture_id,priority:1;comment:都道府県ID - 組織が所属する都道府県" json:"prefecture_id"`  // 都道府県ID - 組織が所属する都道府県
	ParentID     *int32         `gorm:"column:parent_id;type:integer;index:idx_organizations_parent_id,priority:1;comment:親組織ID - 階層構造を表現するための親組織ID" json:"parent_id"`         // 親組織ID - 階層構造を表現するための親組織ID
	Description  *string        `gorm:"column:description;type:text;comment:説明 - 組織の詳細説明" json:"description"`                                                                  // 説明 - 組織の詳細説明
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`          // 作成日時 - レコード作成日時
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`        // 更新日時 - レコード最終更新日時
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:削除日時 - 論理削除用のタイムスタンプ" json:"deleted_at"`                                        // 削除日時 - 論理削除用のタイムスタンプ
	Users        []User         `gorm:"many2many:user_organizations" json:"users"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
