// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupportApplication = "support_applications"

// SupportApplication mapped from table <support_applications>
type SupportApplication struct {
	ApplicationID   string     `gorm:"column:application_id;type:character varying(10);primaryKey;comment:申請ID - 主キー（例：A001, A002...）" json:"application_id"`                                                           // 申請ID - 主キー（例：A001, A002...）
	ApplicationDate time.Time  `gorm:"column:application_date;type:date;not null;index:idx_support_applications_application_date,priority:1;comment:申請日 - 申請が提出された日付" json:"application_date"`                          // 申請日 - 申請が提出された日付
	ApplicantName   string     `gorm:"column:applicant_name;type:character varying(100);not null;comment:申請者名 - 個人名または法人名" json:"applicant_name"`                                                                       // 申請者名 - 個人名または法人名
	DisasterName    string     `gorm:"column:disaster_name;type:character varying(200);not null;index:idx_support_applications_disaster_name,priority:1;comment:災害名 - 対象となる災害の名称" json:"disaster_name"`                 // 災害名 - 対象となる災害の名称
	RequestedAmount int64      `gorm:"column:requested_amount;type:bigint;not null;comment:申請金額 - 申請する支援金額（円）" json:"requested_amount"`                                                                                 // 申請金額 - 申請する支援金額（円）
	Status          string     `gorm:"column:status;type:character varying(20);not null;index:idx_support_applications_status,priority:1;default:審査中;comment:ステータス - 申請の処理状況（審査中、書類確認中、承認済、完了、支払処理中、却下）" json:"status"` // ステータス - 申請の処理状況（審査中、書類確認中、承認済、完了、支払処理中、却下）
	ReviewedAt      *time.Time `gorm:"column:reviewed_at;type:timestamp without time zone;comment:審査完了日時 - 申請の審査が完了した日時" json:"reviewed_at"`                                                                            // 審査完了日時 - 申請の審査が完了した日時
	ApprovedAt      *time.Time `gorm:"column:approved_at;type:timestamp without time zone;comment:承認日時 - 申請が承認された日時" json:"approved_at"`                                                                                // 承認日時 - 申請が承認された日時
	CompletedAt     *time.Time `gorm:"column:completed_at;type:timestamp without time zone;comment:処理完了日時 - 支援金の支払いなど全ての処理が完了した日時" json:"completed_at"`                                                                 // 処理完了日時 - 支援金の支払いなど全ての処理が完了した日時
	Notes           *string    `gorm:"column:notes;type:text;comment:備考 - 申請に関する備考やメモ" json:"notes"`                                                                                                                    // 備考 - 申請に関する備考やメモ
	CreatedAt       time.Time  `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`                                                 // 作成日時 - レコード作成日時
	UpdatedAt       time.Time  `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"`                                               // 更新日時 - レコード最終更新日時
}

// TableName SupportApplication's table name
func (*SupportApplication) TableName() string {
	return TableNameSupportApplication
}
