// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSession = "user_sessions"

// UserSession mapped from table <user_sessions>
type UserSession struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:セッションID（主キー、自動掲番）" json:"id"`                                                           // セッションID（主キー、自動掲番）
	SessionID    string     `gorm:"column:session_id;type:character varying(255);not null;index:idx_user_sessions_session_id,priority:1;comment:セッション識別子（ユニーク制約あり）" json:"session_id"` // セッション識別子（ユニーク制約あり）
	UserID       string     `gorm:"column:user_id;type:uuid;not null;index:idx_user_sessions_user_id,priority:1;comment:ユーザーID（外部キー、ユーザーテーブルのID）" json:"user_id"`                      // ユーザーID（外部キー、ユーザーテーブルのID）
	IPAddress    *string    `gorm:"column:ip_address;type:inet;comment:ユーザーのIPアドレス" json:"ip_address"`                                                                                 // ユーザーのIPアドレス
	UserAgent    *string    `gorm:"column:user_agent;type:text;comment:ユーザーエージェント情報（ブラウザやデバイス情報）" json:"user_agent"`                                                                   // ユーザーエージェント情報（ブラウザやデバイス情報）
	IsActive     *bool      `gorm:"column:is_active;type:boolean;default:true;comment:セッションの有効フラグ（TRUE: 有効、FALSE: 無効）" json:"is_active"`                                               // セッションの有効フラグ（TRUE: 有効、FALSE: 無効）
	ExpiresAt    time.Time  `gorm:"column:expires_at;type:timestamp with time zone;not null;comment:セッションの有効期限" json:"expires_at"`                                                     // セッションの有効期限
	LastActivity *time.Time `gorm:"column:last_activity;type:timestamp with time zone;default:CURRENT_TIMESTAMP;comment:最後のアクティビティ日時（セッションの最終アクティビティ）" json:"last_activity"`           // 最後のアクティビティ日時（セッションの最終アクティビティ）
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP;comment:セッション作成日時" json:"created_at"`                                     // セッション作成日時
}

// TableName UserSession's table name
func (*UserSession) TableName() string {
	return TableNameUserSession
}
