// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	UserID    int32     `gorm:"column:user_id;type:integer;primaryKey;index:idx_user_roles_user_id,priority:1;comment:ユーザーID - ユーザーテーブルの外部キー" json:"user_id"`   // ユーザーID - ユーザーテーブルの外部キー
	RoleID    int32     `gorm:"column:role_id;type:integer;primaryKey;index:idx_user_roles_role_id,priority:1;comment:役割ID - 役割テーブルの外部キー" json:"role_id"`       // 役割ID - 役割テーブルの外部キー
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時 - レコード作成日時" json:"created_at"`   // 作成日時 - レコード作成日時
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時 - レコード最終更新日時" json:"updated_at"` // 更新日時 - レコード最終更新日時
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
