// Code generated by MockGen. DO NOT EDIT.
// Source: facility_equipment.go
//
// Generated by this command:
//
//	mockgen -source=facility_equipment.go -destination=../../../tests/mock/domain/facility_equipment.mock.go
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	model "github.com/AI1411/fullstack-react-go/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFacilityEquipmentRepository is a mock of FacilityEquipmentRepository interface.
type MockFacilityEquipmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacilityEquipmentRepositoryMockRecorder
	isgomock struct{}
}

// MockFacilityEquipmentRepositoryMockRecorder is the mock recorder for MockFacilityEquipmentRepository.
type MockFacilityEquipmentRepositoryMockRecorder struct {
	mock *MockFacilityEquipmentRepository
}

// NewMockFacilityEquipmentRepository creates a new mock instance.
func NewMockFacilityEquipmentRepository(ctrl *gomock.Controller) *MockFacilityEquipmentRepository {
	mock := &MockFacilityEquipmentRepository{ctrl: ctrl}
	mock.recorder = &MockFacilityEquipmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacilityEquipmentRepository) EXPECT() *MockFacilityEquipmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFacilityEquipmentRepository) Create(ctx context.Context, facilityEquipment *model.FacilityEquipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, facilityEquipment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFacilityEquipmentRepositoryMockRecorder) Create(ctx, facilityEquipment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFacilityEquipmentRepository)(nil).Create), ctx, facilityEquipment)
}

// Delete mocks base method.
func (m *MockFacilityEquipmentRepository) Delete(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFacilityEquipmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFacilityEquipmentRepository)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockFacilityEquipmentRepository) Find(ctx context.Context) ([]*model.FacilityEquipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]*model.FacilityEquipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockFacilityEquipmentRepositoryMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockFacilityEquipmentRepository)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockFacilityEquipmentRepository) FindByID(ctx context.Context, id int32) (*model.FacilityEquipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.FacilityEquipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFacilityEquipmentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFacilityEquipmentRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockFacilityEquipmentRepository) Update(ctx context.Context, facilityEquipment *model.FacilityEquipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, facilityEquipment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFacilityEquipmentRepositoryMockRecorder) Update(ctx, facilityEquipment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFacilityEquipmentRepository)(nil).Update), ctx, facilityEquipment)
}
