/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 農業災害支援システム API
 * 農業災害の報告と支援申請を管理するためのAPI
 * OpenAPI spec version: 1.0
 */

export type GetDisastersParams = {
/**
 * 災害名（部分一致検索）
 */
name?: string;
/**
 * 災害種別
 */
disaster_type?: string;
/**
 * ステータス
 */
status?: string;
/**
 * 都道府県ID
 */
prefecture_id?: number;
/**
 * 開始日（RFC3339形式）
 */
start_date?: string;
/**
 * 終了日（RFC3339形式）
 */
end_date?: string;
};
