/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 */

export interface HandlerTimelineResponse {
  description?: string;
  disaster_id?: string;
  event_name?: string;
  event_time?: string;
  id?: number;
  severity?: string;
}
