/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 */
import type { HandlerSupportApplicationResponse } from './handlerSupportApplicationResponse';

export interface HandlerListSupportApplicationsResponse {
  support_applications?: HandlerSupportApplicationResponse[];
  total?: number;
}
