/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 */
import type { HandlerDisasterResponse } from './handlerDisasterResponse';

export interface HandlerListDisastersResponse {
  disasters?: HandlerDisasterResponse[];
  total?: number;
}
