/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 */
import type { HandlerRegionItem } from "./handlerRegionItem"

export interface HandlerPrefectureItem {
  name: string
  region: HandlerRegionItem
}
