/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 */

export interface HandlerCreateSupportApplicationRequest {
  applicant_name: string
  application_date: string
  application_id: string
  disaster_name: string
  notes?: string
  requested_amount: number
  status?: string
}
